name: MLOps CI/CD Pipeline

# Trigger this workflow every time you push code to the 'main' branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # -------------------------------------------
  # JOB 1: Test the Code and Model
  # -------------------------------------------
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest httpx
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          # This is the exact magic command that just worked for you locally!
          python -m pytest tests/

  # -------------------------------------------
  # JOB 2: Build and Push Docker Container
  # -------------------------------------------
  build-and-push:
    needs: test-api # This ensures Docker only builds IF the tests pass!
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # We will set these secrets in GitHub next
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/iris-model-api:latest